blank_issues_enabled: true
contact_links:
  - name: 💬 Questions & Support
    url: https://community.home-assistant.io/t/lunar-phase-integration-for-home-assistant
    about: For questions, help, and discussions about card, please use dedicated Home Assistant community forum thread, feel free to tag me @ngocjohn.
  - name: 📚 Documentation
    url: https://github.com/ngocjohn/lunar-phase-card?tab=readme-ov-file#configuration
    about: Check the README for detailed configuration options and examples.